apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
  containers:
  - name: container-1
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: container-2
    image: busybox:latest
    command: ['sh', '-c', 'while true; do echo $(date) >> /mnt/data/index.html; sleep 1; done']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/data
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: shared-data
    emptyDir: {}
